version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=my-cluster
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false" # Disable X-Pack security
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/es1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=my-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false" # Disable X-Pack security
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/es2:/usr/share/elasticsearch/data
    networks:
      - esnet

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=my-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false" # Disable X-Pack security
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/es3:/usr/share/elasticsearch/data
    networks:
      - esnet

networks:
  esnet: